# Generated by Django 4.1 on 2022-08-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_socio', models.IntegerField()),
                ('fecha_cuota', models.DateField()),
                ('deporte', models.CharField(max_length=30)),
                ('pago', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Diciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deporte', models.CharField(max_length=30)),
                ('lugar', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Directivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('n_socio', models.IntegerField()),
                ('cargo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Socios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('n_socio', models.IntegerField()),
                ('fecha_ingreso', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
